# H2 In-Memory Database for Development (spring.profiles.active=h2)
spring.datasource.url=jdbc:h2:mem:smartcampusdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Google OAuth2 Credentials for dev
spring.security.oauth2.client.registration.google.client-id=599962475515-naddjn8nn5h0aetd6pinq49mff57sl34.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

logging.level.org.springframework.security=INFO
