version: '3.8'

services:
  app:
    build: .
    container_name: smartcampus-app
    ports:
      - "8099:8099"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/SmartCampusOperationsHub
      SPRING_DATASOURCE_USERNAME: webuser
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
